interface Serializable
{
    +load(istream): int
    +dump(ostream): int
}

class Record
{
    -key: int
    -data: char[12]
    +getter()
    +operator_cmp()
    +operator=()
}

interface AbstractBlock
{
    __
    +load(istream): int
    +dump(ostream): int
    ..
    +count(): size_t
    +setCount(num): size_t
    +size(): size_t
    +operator[](i): Record&
}

class Block
{
    -cnt: size_t
    -size: size_t
    -record_array: Record[size]
}

class BlockDecorator
{
    #block: AbstractBlock
}

class SortableBlock
{
    +sort(): void
}

interface PopOnlyStack<T>
{
    +top(): T
    +pop(): void
    +empty(): bool
}

class IterableBlock
{
    #m_top_index: size_t
    __
    +top(): Record
    +pop(): void
    +empty(): bool
    ..
    +count(): size_t
}

Serializable <|.. Record
Serializable <|-- AbstractBlock
AbstractBlock <|.. BlockDecorator
AbstractBlock <-- BlockDecorator

BlockDecorator <|-- SortableBlock
BlockDecorator <|- IterableBlock

Record <. AbstractBlock
AbstractBlock <|.. Block

PopOnlyStack <|.. IterableBlock

Record -o Block